lesson 1 , task 4
js-tasks-ru/jsbasic-20220711_emmanuil-kremov pull request #4
Opened 2022-07-14 21:00 UTC by EKremov

2022-07-14 21:00 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-07-15 09:09 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-07-15 09:53 UTC, SinimaWath requested changes

2022-07-15 09:53 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  str = str.toLowerCase();
Присваивание значений аргументам функций, это считается антипаттерном - плохим, тоном. Который может привести к неявным багам.

Лучше создать новую переменную

2022-07-15 09:53 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  }
метод includes - уже возвращает boolean, в качестве результата, поэтому твое выражение имеет такой вид:
`boolean || boolean`. И так как результат будет boolean, нет необходимости в if.

`return str.includes('1xbet') || str.includes('xxx')`;

2022-07-15 12:07 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-07-15 13:43 UTC, SinimaWath approved these changes

2022-07-15 13:44 UTC, merged